"""
report.py — HTML report generation with embedded Plotly interactive charts.
"""

from __future__ import annotations

import re
from typing import Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# HTML Report
# ---------------------------------------------------------------------------

# NOTE: Placeholders use __TITLE__ / __CONTENT__ (not {}) so that Plotly's
# embedded JSON (which is full of { }) cannot be corrupted by str.format().
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>__TITLE__</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        *, *:before, *:after { box-sizing: inherit; }
        html { box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: #0d1117; color: #c9d1d9;
            max-width: 1200px; margin: 0 auto; padding: 2rem;
            line-height: 1.6;
        }
        h1 {
            color: #58a6ff; font-size: 2rem;
            border-bottom: 2px solid #30363d; padding-bottom: 0.75rem;
            margin-bottom: 1.5rem;
        }
        h2 {
            color: #f0883e; font-size: 1.4rem;
            margin: 2rem 0 1rem; padding-bottom: 0.4rem;
            border-bottom: 1px solid #21262d;
        }
        h3 { color: #a371f7; font-size: 1.1rem; margin: 1.2rem 0 0.5rem; }
        p, li { color: #c9d1d9; margin-bottom: 0.5rem; }
        strong { color: #f0f6fc; }
        em { color: #8b949e; }
        ul { padding-left: 1.5rem; margin-bottom: 1rem; }
        table {
            border-collapse: collapse; width: 100%; margin: 1rem 0;
            font-size: 0.85rem;
        }
        th, td { border: 1px solid #30363d; padding: 8px 12px; text-align: left; }
        th { background: #161b22; color: #58a6ff; font-weight: 600; }
        tr:nth-child(even) { background: #161b22; }
        tr:hover { background: #1c2333; }
        .metrics-grid {
            display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 1rem; margin: 1.5rem 0;
        }
        .metric {
            background: linear-gradient(135deg, #161b22 0%, #1c2333 100%);
            border: 1px solid #30363d; border-radius: 12px;
            padding: 1.2rem; text-align: center;
        }
        .metric-value {
            font-size: 1.6rem; font-weight: 700; color: #f0f6fc;
            margin-bottom: 0.3rem;
        }
        .metric-label {
            font-size: 0.8rem; color: #8b949e;
            text-transform: uppercase; letter-spacing: 0.05em;
        }
        .summary {
            background: #161b22; border-left: 4px solid #58a6ff;
            padding: 1.2rem 1.5rem; margin: 1rem 0;
            border-radius: 0 10px 10px 0;
        }
        .plot-container {
            background: #161b22; border: 1px solid #30363d;
            border-radius: 12px; padding: 1rem; margin: 1.5rem 0;
        }
        .plot-title {
            color: #8b949e; font-size: 0.85rem; text-transform: uppercase;
            letter-spacing: 0.05em; margin-bottom: 0.5rem; font-weight: 600;
        }
        .footer {
            margin-top: 3rem; padding-top: 1rem;
            border-top: 1px solid #21262d;
            color: #484f58; font-size: 0.8rem; text-align: center;
        }
    </style>
</head>
<body>
    <h1>__TITLE__</h1>
    __CONTENT__
    <div class="footer">
        Generated by EEG Analysis Dashboard
    </div>
</body>
</html>"""


def generate_html_report(
    title: str = "EEG Analysis Report",
    rec_metadata: dict | None = None,
    summary_text: str = "",
    band_power_table: pd.DataFrame | None = None,
    anomaly_summary: dict | None = None,
    plotly_divs: list[tuple[str, str]] | None = None,
) -> str:
    """Generate a comprehensive HTML report with embedded interactive Plotly charts."""
    sections = []

    # ── Recording Metrics ──────────────────────────────────────────────
    if rec_metadata:
        metrics_html = '<div class="metrics-grid">'
        display_keys = {
            "format": "Format",
            "n_channels": "Channels",
            "sfreq": "Sample Rate",
            "total_samples": "Total Samples",
            "duration_s": "Duration",
            "file": "Source File",
        }
        for key, label in display_keys.items():
            if key in rec_metadata:
                val = rec_metadata[key]
                if key == "format":
                    val = str(val).upper()
                elif key == "sfreq":
                    val = f"{val:.0f} Hz"
                elif key == "duration_s":
                    val = f"{val:.1f} s"
                elif key == "total_samples":
                    val = f"{val:,}"
                metrics_html += (
                    f'<div class="metric">'
                    f'<div class="metric-value">{val}</div>'
                    f'<div class="metric-label">{label}</div>'
                    f'</div>'
                )
        metrics_html += '</div>'
        sections.append(f"<h2>Recording Information</h2>{metrics_html}")

    # ── Analysis Summary ───────────────────────────────────────────────
    if summary_text:
        html_summary = summary_text.replace("\n", "<br>")
        html_summary = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_summary)
        html_summary = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_summary)
        sections.append(f'<h2>Analysis Summary</h2><div class="summary">{html_summary}</div>')

    # ── Interactive Plots ──────────────────────────────────────────────
    if plotly_divs:
        sections.append("<h2>Analysis Plots</h2>")
        for plot_title, plot_html in plotly_divs:
            sections.append(
                f'<div class="plot-container">'
                f'<div class="plot-title">{plot_title}</div>'
                f'{plot_html}'
                f'</div>'
            )

    # ── Band Power Table ───────────────────────────────────────────────
    if band_power_table is not None and not band_power_table.empty:
        table_html = band_power_table.to_html(float_format="%.4e")
        sections.append(f"<h2>Band Power Summary</h2>{table_html}")

    # ── Anomaly Summary ────────────────────────────────────────────────
    if anomaly_summary:
        anom_html = '<div class="metrics-grid">'
        for key, val in anomaly_summary.items():
            anom_html += (
                f'<div class="metric">'
                f'<div class="metric-value">{val}</div>'
                f'<div class="metric-label">{key}</div>'
                f'</div>'
            )
        anom_html += '</div>'
        sections.append(f"<h2>Anomaly Detection Results</h2>{anom_html}")

    content = "\n".join(sections)
    # Use replace() — NOT format() — so Plotly's embedded JSON {}/[] are preserved
    return (
        _HTML_TEMPLATE
        .replace("__TITLE__", title)
        .replace("__CONTENT__", content)
    )
